name: tafakkur_lms
description: "Tafakkur LMS dashboard app (HeroUI-styled Flutter client)."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  go_router: ^18.0.1
  google_fonts: ^8.2.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
