# frozen_string_literal: true

source "https://rubygems.org"

gem "bootsnap", require: false
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rails", "~> 8.1.1"
gem "tzinfo-data", platforms: %i[windows jruby]

# Authentication
gem "bcrypt", "~> 3.1"
gem "devise"
gem "devise-jwt"

# Authorization
gem "pundit"

# Business logic
gem "interactor", "~> 3.0"
gem "interactor-rails", "~> 2.3"

# API
gem "jbuilder"
gem "kaminari"
gem "rswag-api"
gem "rswag-ui"
gem "versionist"

# Background jobs
gem "redis", ">= 4.0.1"
gem "sidekiq", "~> 7.3", ">= 7.3.10"
gem "sidekiq-cron"

# Soft delete
gem "discard", "~> 1.3"

# Security
gem "rack-attack"
gem "rack-cors"

# Logging
gem "lograge"

# Email
gem "resend"

group :development, :test do
    gem "brakeman", require: false
    gem "bullet"
    gem "bundler-audit", require: false
    gem "debug", platforms: %i[mri windows], require: "debug/prelude"
    gem "dotenv-rails"
    gem "factory_bot_rails"
    gem "faker"
    gem "foreman"
    gem "rspec-rails", "~> 7.0"
    gem "rswag-specs"
    gem "rubocop", require: false
    gem "rubocop-rails", require: false
    gem "rubocop-rspec", require: false
end

group :test do
    gem "shoulda-matchers", "~> 6.0"
end
